addons:
  ssh_known_hosts:
  - "$DEPLOY_HOST"
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules  
before_install:
- openssl aes-256-cbc -K $encrypted_0178fc6b0616_key -iv $encrypted_0178fc6b0616_iv
  -in id_rsa_main.enc -out ~/.ssh/id_rsa_main -d
- chmod 600 ~/.ssh/id_rsa_main  
script:
- npm test
- npm run build  
deploy: 
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after --rsh='ssh -p 22 -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_main' $TRAVIS_BUILD_DIR/build $SSH_USER@$DEPLOY_HOST:/www/tool
  on:
    branch: master
